# Generated by Django 5.2.8 on 2025-11-15 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('financial_market', models.CharField(choices=[('B3', 'B3'), ('Nasdaq', 'Nasdaq'), ('NYExchange', 'NYSE')], default='B3', max_length=20)),
                ('stock_class', models.CharField(choices=[('ON', 'ON'), ('PN', 'PN'), ('ETF', 'ETF'), ('BDR', 'BDR')], default='ON', max_length=10)),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('investment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='configuration.investmenttype')),
            ],
            options={
                'db_table': 'stock_catalog',
                'ordering': ['ticker'],
            },
        ),
    ]
