# Generated by Django 5.2.8 on 2025-11-21 15:58

from django.db import migrations
from django.db.models import Q


def migrate_investment_types_forward(apps, schema_editor):
    """Migrate investment types to new hierarchical structure."""
    InvestmentType = apps.get_model('configuration', 'InvestmentType')
    InvestmentSubType = apps.get_model('configuration', 'InvestmentSubType')
    Stock = apps.get_model('stocks', 'Stock')
    
    # Create new Investment Types
    renda_variavel_reais, _ = InvestmentType.objects.get_or_create(
        code='RENDA_VARIAVEL_REAIS',
        defaults={
            'name': 'Renda Variável em Reais',
            'display_order': 10,
            'is_active': True
        }
    )
    
    renda_variavel_dolares, _ = InvestmentType.objects.get_or_create(
        code='RENDA_VARIAVEL_DOLARES',
        defaults={
            'name': 'Renda Variável em Dólares',
            'display_order': 20,
            'is_active': True
        }
    )
    
    # Create Investment Subtypes
    acoes_reais_subtype, _ = InvestmentSubType.objects.get_or_create(
        investment_type=renda_variavel_reais,
        code='ACOES_REAIS',
        defaults={
            'name': 'Ações em Reais',
            'display_order': 10,
            'is_predefined': True,
            'is_active': True
        }
    )
    
    bdrs_subtype, _ = InvestmentSubType.objects.get_or_create(
        investment_type=renda_variavel_dolares,
        code='BDRS',
        defaults={
            'name': 'BDRs',
            'display_order': 10,
            'is_predefined': True,
            'is_active': True
        }
    )
    
    # Find and migrate existing "Ações em Reais" stocks
    acoes_reais_type = InvestmentType.objects.filter(
        Q(code__icontains='ACOES') | Q(name__icontains='Ações em Reais')
    ).first()
    
    if acoes_reais_type:
        stocks_acoes_reais = Stock.objects.filter(investment_type=acoes_reais_type)
        updated_count = stocks_acoes_reais.update(
            investment_type=renda_variavel_reais,
            investment_subtype=acoes_reais_subtype
        )
        print(f"Migrated {updated_count} stocks from 'Ações em Reais' to 'Renda Variável em Reais' with subtype 'Ações em Reais'")
    
    # Find and migrate existing "Ações em Dólares" stocks
    acoes_dolares_type = InvestmentType.objects.filter(
        Q(code__icontains='DOLARES') | Q(name__icontains='Ações em Dólares') | Q(name__icontains='Ações em Dólares')
    ).first()
    
    if acoes_dolares_type:
        stocks_acoes_dolares = Stock.objects.filter(investment_type=acoes_dolares_type)
        updated_count = stocks_acoes_dolares.update(
            investment_type=renda_variavel_dolares,
            investment_subtype=bdrs_subtype
        )
        print(f"Migrated {updated_count} stocks from 'Ações em Dólares' to 'Renda Variável em Dólares' with subtype 'BDRs'")


def migrate_investment_types_reverse(apps, schema_editor):
    """Reverse migration - restore old investment types."""
    InvestmentType = apps.get_model('configuration', 'InvestmentType')
    InvestmentSubType = apps.get_model('configuration', 'InvestmentSubType')
    Stock = apps.get_model('stocks', 'Stock')
    
    # Find new types
    renda_variavel_reais = InvestmentType.objects.filter(code='RENDA_VARIAVEL_REAIS').first()
    renda_variavel_dolares = InvestmentType.objects.filter(code='RENDA_VARIAVEL_DOLARES').first()
    
    # Find old types if they exist
    acoes_reais_type = InvestmentType.objects.filter(
        Q(code__icontains='ACOES') | Q(name__icontains='Ações em Reais')
    ).exclude(code='RENDA_VARIAVEL_REAIS').first()
    
    acoes_dolares_type = InvestmentType.objects.filter(
        Q(code__icontains='DOLARES') | Q(name__icontains='Ações em Dólares')
    ).exclude(code='RENDA_VARIAVEL_DOLARES').first()
    
    # Revert stock migrations
    if renda_variavel_reais and acoes_reais_type:
        stocks = Stock.objects.filter(investment_type=renda_variavel_reais)
        stocks.update(
            investment_type=acoes_reais_type,
            investment_subtype=None
        )
    
    if renda_variavel_dolares and acoes_dolares_type:
        stocks = Stock.objects.filter(investment_type=renda_variavel_dolares)
        stocks.update(
            investment_type=acoes_dolares_type,
            investment_subtype=None
        )
    
    # Delete new subtypes (if they exist)
    InvestmentSubType.objects.filter(code='ACOES_REAIS').delete()
    InvestmentSubType.objects.filter(code='BDRS').delete()
    
    # Delete new investment types (if they exist)
    if renda_variavel_reais:
        renda_variavel_reais.delete()
    if renda_variavel_dolares:
        renda_variavel_dolares.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        ('stocks', '0002_stock_investment_subtype'),
    ]

    operations = [
        migrations.RunPython(migrate_investment_types_forward, migrate_investment_types_reverse),
    ]
