# Generated by Django 5.2.8 on 2025-11-26 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_ensure_subtypes_exist'),
        ('stocks', '0003_migrate_investment_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='investment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='configuration.investmenttype'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_class',
            field=models.CharField(choices=[('ON', 'ON'), ('PN', 'PN'), ('ETF', 'ETF'), ('BDR', 'BDR'), ('FII', 'FII')], default='ON', max_length=10),
        ),
    ]
