# Generated by Django 5.2.8 on 2025-11-21 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investment_subtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crypto_currencies', to='configuration.investmentsubtype')),
                ('investment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crypto_currencies', to='configuration.investmenttype')),
            ],
            options={
                'verbose_name': 'Crypto Currency',
                'verbose_name_plural': 'Crypto Currencies',
                'db_table': 'crypto_currencies',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='CryptoOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('operation_type', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venda')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('operation_date', models.DateField()),
                ('broker', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crypto_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='crypto.cryptocurrency')),
            ],
            options={
                'db_table': 'crypto_operations',
                'ordering': ['-operation_date', '-created_at'],
                'indexes': [models.Index(fields=['user_id', 'operation_date'], name='crypto_oper_user_id_4d876b_idx'), models.Index(fields=['crypto_currency', 'operation_date'], name='crypto_oper_crypto__61ae27_idx')],
            },
        ),
        migrations.CreateModel(
            name='CryptoPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('average_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('broker', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crypto_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='crypto.cryptocurrency')),
            ],
            options={
                'db_table': 'crypto_positions',
                'ordering': ['crypto_currency__symbol'],
                'indexes': [models.Index(fields=['user_id'], name='crypto_posi_user_id_04d3c7_idx'), models.Index(fields=['crypto_currency'], name='crypto_posi_crypto__09f9e5_idx')],
                'unique_together': {('user_id', 'crypto_currency')},
            },
        ),
    ]
