# Generated by Django 5.2.8 on 2025-11-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptooperation',
            name='quantity',
            field=models.DecimalField(decimal_places=18, max_digits=30),
        ),
        migrations.AlterField(
            model_name='cryptoposition',
            name='quantity',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=30),
        ),
    ]
