from django.core.management.base import BaseCommand
from ticker_mappings.services import TickerMappingService

class Command(BaseCommand):
    help = 'Seeds the database with common B3 company-to-ticker mappings'

    def handle(self, *args, **kwargs):
        # Dictionary of Company Name -> Ticker
        # Note: Names are normalized (uppercase, single spaces) during save
        common_mappings = {
            "PETROLEO BRASILEIRO S.A. PETROBRAS": "PETR4",
            "PETROBRAS PN": "PETR4",
            "PETROBRAS ON": "PETR3",
            "VALE S.A.": "VALE3",
            "ITAU UNIBANCO HOLDING S.A.": "ITUB4",
            "ITAU UNIBANCO PN": "ITUB4",
            "ITAU UNIBANCO ON": "ITUB3",
            "BANCO BRADESCO S.A.": "BBDC4",
            "BRADESCO PN": "BBDC4",
            "BRADESCO ON": "BBDC3",
            "B3 S.A. - BRASIL, BOLSA, BALCAO": "B3SA3",
            "AMBEV S.A.": "ABEV3",
            "WEG S.A.": "WEGE3",
            "ITAUSA S.A.": "ITSA4",
            "ITAUSA PN": "ITSA4",
            "BANCO DO BRASIL S.A.": "BBAS3",
            "GERDAU S.A.": "GGBR4",
            "GERDAU PN": "GGBR4",
            "SUZANO S.A.": "SUZB3",
            "LOCALIZA RENT A CAR S.A.": "RENT3",
            "JBS S.A.": "JBSS3",
            "RAIA DROGASIL S.A.": "RADL3",
            "RUMO S.A.": "RAIL3",
            "COSAN S.A.": "CSAN3",
            "BTG PACTUAL": "BPAC11",
            "BANCO BTG PACTUAL S.A.": "BPAC11",
            "VIBRA ENERGIA S.A.": "VBBR3",
            "EQUATORIAL ENERGIA S.A.": "EQTL3",
            "LOJAS RENNER S.A.": "LREN3",
            "TELEFONICA BRASIL S.A.": "VIVT3",
            "TIM S.A.": "TIMS3",
            "CCR S.A.": "CCRO3",
            "SABESP": "SBSP3",
            "CIA SANEAMENTO BASICO ESTADO SAO PAULO": "SBSP3",
            "ELETROBRAS": "ELET3",
            "CENTRAIS ELETRICAS BRASILEIRAS S.A.": "ELET3",
            "ELETROBRAS PNB": "ELET6",
            "MAGAZINE LUIZA S.A.": "MGLU3",
            "NATURA &CO HOLDING S.A.": "NTCO3",
            "HAPVIDA PARTICIPACOES E INVESTIMENTOS S.A.": "HAPV3",
            "PETRORIO S.A.": "PRIO3",
            "BB SEGURIDADE PARTICIPACOES S.A.": "BBSE3",
            "HYPERA S.A.": "HYPE3",
            "ENGIE BRASIL ENERGIA S.A.": "EGIE3",
            "CPFL ENERGIA S.A.": "CPFE3",
            "KLABIN S.A.": "KLBN11",
            "ULTRAPAR PARTICIPACOES S.A.": "UGPA3",
            "TOTVS S.A.": "TOTS3",
            "EMBRAER S.A.": "EMBR3",
            "SANTANDER BRASIL": "SANB11",
            "BANCO SANTANDER (BRASIL) S.A.": "SANB11",
            "MULTIPLAN": "MULT3",
            "IGUATEMI": "IGTI11",
            "CYRELA": "CYRE3",
            "MRV ENGENHARIA": "MRVE3",
            "EZTEC": "EZTC3",
            "FLEURY": "FLRY3",
            "QUALICORP": "QUAL3",
            "COGNA EDUCACAO": "COGN3",
            "YDUQS": "YDUQ3",
            "CSN MINERACAO": "CMIN3",
            "CSN": "CSNA3",
            "USIMINAS PNA": "USIM5",
            "USINAS SIDERURGICAS DE MINAS GERAIS S.A.": "USIM5",
            "TAESA": "TAEE11",
            "TRANSMISSORA ALIANCA DE ENERGIA ELETRICA S.A.": "TAEE11",
            "CEMIG PN": "CMIG4",
            "COMPANHIA ENERGETICA DE MINAS GERAIS": "CMIG4",
            "COPEL PNB": "CPLE6",
            "SANEPAR UNIT": "SAPR11",
            "SANEPAR PN": "SAPR4",
            "BANRISUL PNB": "BRSR6",
            "CAIXA SEGURIDADE": "CXSE3",
            "ALPARGATAS PN": "ALPA4",
            "GRENDENE": "GRND3",
            "AREZZO": "ARZZ3",
            "SOMA": "SOMA3",
            "PETZ": "PETZ3",
            "ASSAI": "ASAI3",
            "CARREFOUR BRASIL": "CRFB3",
            "PÃO DE AÇÚCAR": "PCAR3",
            "SENDAS DISTRIBUIDORA": "ASAI3",
            "3R PETROLEUM": "RRRP3",
            "ENAUTA": "ENAT3",
            "SLC AGRICOLA": "SLCE3",
            "SAO MARTINHO": "SMTO3",
            "MINERVA": "BEEF3",
            "MARFRIG": "MRFG3",
            "BRF S.A.": "BRFS3",
            "M. DIAS BRANCO": "MDIA3",
            "CAMIL": "CAML3",
            "AMBPOLAR": "AMBP3",
            "AZUL": "AZUL4",
            "GOL": "GOLL4",
            "CVC BRASIL": "CVCB3",
            "IRB BRASIL": "IRBR3",
            "PORTO SEGURO": "PSSA3",
            "SUL AMERICA": "SULA11",
            "B3": "B3SA3",
            "3TENTOS ON NM": "TTEN3",
            "AERIS ON NM": "AERI3",
            "ALOS ON NM": "ALOS3",
            "ALPARGATAS PN N1": "ALPA4",
            "AMBEV S/A ON": "ABEV3",
            "AMBEV S/A ON EJ": "ABEV3",
            "AMBPOLAR ON NM": "AMBP3",
            "ANIMA ON NM": "ANIM3",
            "AREZZO CO ON NM": "ARZZ3",
            "ARMAC ON NM": "ARML3",
            "ASSAI ON NM": "ASAI3",
            "AUREN ON NM": "AURE3",
            "AZUL PN N2": "AZUL4",
            "B3 ON NM": "B3SA3",
            "BANCO INTER UNIT N2": "BIDI11",
            "BBSEGURIDADE ON NM": "BBSE3",
            "BEEF ON NM": "BEEF3",
            "BLAU ON NM": "BLAU3",
            "BRADESCO ON N1": "BBDC3",
            "BRADESCO PN N1": "BBDC4",
            "BRADESPAR PN N1": "BRAP4",
            "BRASIL ON NM": "BBAS3",
            "BRF SA ON NM": "BRFS3",
            "BTGPACTUAL UNT N2": "BPAC11",
            "CAIXA SEGURIDADE ON NM": "CXSE3",
            "CAMIL ON NM": "CAML3",
            "CARREFOUR BR ON NM": "CRFB3",
            "CCR SA ON NM": "CCRO3",
            "CEA MODAS ON NM": "CEAB3",
            "CEMIG PN N1": "CMIG4",
            "CIELO ON NM": "CIEL3",
            "COGNA ON NM": "COGN3",
            "COPEL PNB N1": "CPLE6",
            "COSAN ON NM": "CSAN3",
            "CPFL ENERGIA ON NM": "CPFE3",
            "CSN MINERACAO ON N2": "CMIN3",
            "CSN ON NM": "CSNA3",
            "CURY ON NM": "CURY3",
            "CVC BRASIL ON NM": "CVCB3",
            "CYRELA REALT ON NM": "CYRE3",
            "DEXCO ON NM": "DXCO3",
            "DIRECIONAL ON NM": "DIRR3",
            "ECORODOVIAS ON NM": "ECOR3",
            "ELETROBRAS ON N1": "ELET3",
            "ELETROBRAS PNB N1": "ELET6",
            "EMBRAER ON NM": "EMBR3",
            "ENAUTA PART ON NM": "ENAT3",
            "ENEVA ON NM": "ENEV3",
            "ENGIE BRASIL ON NM": "EGIE3",
            "EQUATORIAL ON NM": "EQTL3",
            "EZTEC ON NM": "EZTC3",
            "FERBASA PN N1": "FESA4",
            "FLEURY ON NM": "FLRY3",
            "GERDAU MET PN N1": "GOAU4",
            "GERDAU PN N1": "GGBR4",
            "GOL PN N2": "GOLL4",
            "GPS ON NM": "GGPS3",
            "GRUPO MATEUS ON NM": "GMAT3",
            "GRUPO NATURA ON NM": "NTCO3",
            "GRUPO SOMA ON NM": "SOMA3",
            "HAPVIDA ON NM": "HAPV3",
            "HYPERA ON NM": "HYPE3",
            "IGUATEMI S.A UNT N1": "IGTI11",
            "INTELBRAS ON NM": "INTB3",
            "IOCHP-MAXION ON NM": "MYPK3",
            "IRBBRASIL RE ON NM": "IRBR3",
            "ITAUUNIBANCO ON N1": "ITUB3",
            "ITAUUNIBANCO PN N1": "ITUB4",
            "ITAUSA ON N1": "ITSA3",
            "ITAUSA PN N1": "ITSA4",
            "JBS ON NM": "JBSS3",
            "JHSF PART ON NM": "JHSF3",
            "KLABIN S/A UNT N2": "KLBN11",
            "LOCALIZA ON NM": "RENT3",
            "LOCAWEB ON NM": "LWSA3",
            "LOJAS RENNER ON NM": "LREN3",
            "LUPATECH ON NM": "LUPA3",
            "M.DIASBRANCO ON NM": "MDIA3",
            "MAGAZ LUIZA ON NM": "MGLU3",
            "MARFRIG ON NM": "MRFG3",
            "METAL LEVE ON NM": "LEVE3",
            "MINERVA ON NM": "BEEF3",
            "MOVIDA ON NM": "MOVI3",
            "MRV ON NM": "MRVE3",
            "MULTIPLAN ON N2": "MULT3",
            "NEOGRID ON NM": "NGRD3",
            "NEOENERGIA ON NM": "NEOE3",
            "ODONTOPREV ON NM": "ODPV3",
            "OMEGAENERGIA ON NM": "MEGA3",
            "ONCOCLINICAS ON NM": "ONCO3",
            "ORIZON ON NM": "ORVR3",
            "P.ACUCAR-CBD ON NM": "PCAR3",
            "PETROBRAS ON N2": "PETR3",
            "PETROBRAS PN N2": "PETR4",
            "PETRORECONCA ON NM": "RECV3",
            "PETRORIO ON NM": "PRIO3",
            "PETZ ON NM": "PETZ3",
            "PLANO E PLAN ON NM": "PLPL3",
            "PORTO SEGURO ON NM": "PSSA3",
            "POSITIVO TEC ON NM": "POSI3",
            "PRIO ON NM": "PRIO3",
            "QUALICORP ON NM": "QUAL3",
            "RAIA DROGASIL ON NM": "RADL3",
            "RAIZEN PN N2": "RAIZ4",
            "RANDON PART PN N1": "RAPT4",
            "REDE D OR ON NM": "RDOR3",
            "RUMO S.A. ON NM": "RAIL3",
            "SABESP ON NM": "SBSP3",
            "SANEPAR PN N2": "SAPR4",
            "SANEPAR UNT N2": "SAPR11",
            "SANTANDER BR UNT": "SANB11",
            "SANTOS BRP ON NM": "STBP3",
            "SAO MARTINHO ON NM": "SMTO3",
            "SENDAS ON NM": "ASAI3",
            "SEQUOIA LOG ON NM": "SEQL3",
            "SIMPAR ON NM": "SIMH3",
            "SLC AGRICOLA ON NM": "SLCE3",
            "SMART FIT ON NM": "SMFT3",
            "SUL AMERICA UNT N2": "SULA11",
            "SUZANO S.A. ON NM": "SUZB3",
            "TAESA UNT N2": "TAEE11",
            "TELEF BRASIL ON": "VIVT3",
            "TIM ON NM": "TIMS3",
            "TOTVS ON NM": "TOTS3",
            "TRAN PAULIST PN N1": "TRPL4",
            "TRES TENTOS ON NM": "TTEN3",
            "TUPY ON NM": "TUPY3",
            "ULTRAPAR ON NM": "UGPA3",
            "UNIPAR PNB": "UNIP6",
            "USIMINAS PNA N1": "USIM5",
            "VALE ON NM": "VALE3",
            "VAMOS ON NM": "VAMO3",
            "VIA ON NM": "VIIA3",
            "VIBRA ON NM": "VBBR3",
            "VIVARA S.A. ON NM": "VIVA3",
            "WEG ON NM": "WEGE3",
            "YDUQS PART ON NM": "YDUQ3",
        }

        self.stdout.write('Seeding ticker mappings...')
        
        # Save all mappings
        TickerMappingService.save_mappings(common_mappings)
        
        self.stdout.write(self.style.SUCCESS(f'Successfully seeded {len(common_mappings)} ticker mappings'))


