# Generated by Django 5.2.8 on 2025-11-15 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedIncomePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_code', models.CharField(db_index=True, max_length=100)),
                ('application_date', models.DateField()),
                ('grace_period_end', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField()),
                ('price_date', models.DateField(blank=True, null=True)),
                ('rate', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('available_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('guarantee_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('applied_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('position_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gross_yield', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_yield', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('iof', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('rating', models.CharField(blank=True, max_length=100, null=True)),
                ('liquidity', models.CharField(blank=True, max_length=100, null=True)),
                ('interest', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(default='Manual Entry', max_length=50)),
                ('import_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investment_sub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_income_positions', to='configuration.investmentsubtype')),
                ('investment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_income_positions', to='configuration.investmenttype')),
            ],
            options={
                'db_table': 'fixed_income_positions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TesouroDiretoPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_name', models.CharField(max_length=255)),
                ('vencimento', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixed_income_position', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tesouro_direto', to='fixed_income.fixedincomeposition')),
            ],
            options={
                'db_table': 'tesouro_direto_positions',
                'ordering': ['vencimento'],
            },
        ),
        migrations.AddIndex(
            model_name='fixedincomeposition',
            index=models.Index(fields=['user_id', 'asset_code'], name='fixed_incom_user_id_84bc38_idx'),
        ),
        migrations.AddIndex(
            model_name='fixedincomeposition',
            index=models.Index(fields=['user_id', 'investment_type'], name='fixed_incom_user_id_5848fe_idx'),
        ),
        migrations.AddIndex(
            model_name='fixedincomeposition',
            index=models.Index(fields=['maturity_date'], name='fixed_incom_maturit_f1d00b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fixedincomeposition',
            unique_together={('user_id', 'asset_code', 'application_date')},
        ),
        migrations.AddIndex(
            model_name='tesourodiretoposition',
            index=models.Index(fields=['titulo_name', 'vencimento'], name='tesouro_dir_titulo__b6aa51_idx'),
        ),
    ]
