# Generated by Django 5.2.8 on 2025-12-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_income', '0003_assign_caixa_subtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(max_length=255)),
                ('fund_cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('fund_type', models.CharField(choices=[('RF_POS', 'Renda Fixa Pós-Fixado'), ('RF_PRE', 'Renda Fixa Prefixado'), ('RF_IPCA', 'Renda Fixa IPCA+'), ('MULTI', 'Multimercado'), ('ACOES', 'Ações'), ('CAMBIO', 'Câmbio'), ('OTHER', 'Outros')], default='RF_POS', max_length=20)),
                ('quota_date', models.DateField(blank=True, null=True)),
                ('quota_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('quota_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('in_quotation', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('position_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('applied_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gross_return_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_return_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('source', models.CharField(default='Excel Import', max_length=50)),
                ('import_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'investment_funds',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'fund_name'], name='investment__user_id_66a6d3_idx'), models.Index(fields=['user_id', 'fund_type'], name='investment__user_id_5e5125_idx'), models.Index(fields=['quota_date'], name='investment__quota_d_38194b_idx')],
                'unique_together': {('user_id', 'fund_name', 'quota_date')},
            },
        ),
    ]
