# Generated by Django 5.2.8 on 2025-12-03 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_ensure_subtypes_exist'),
        ('fixed_income', '0004_investmentfund'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentfund',
            name='investment_sub_type',
            field=models.ForeignKey(blank=True, help_text='Subtipo de investimento configurado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investment_funds', to='configuration.investmentsubtype'),
        ),
        migrations.AddField(
            model_name='investmentfund',
            name='investment_type',
            field=models.ForeignKey(blank=True, help_text='Tipo de investimento configurado (ex: Renda Fixa)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investment_funds', to='configuration.investmenttype'),
        ),
    ]
