# Generated by Django 5.2.8 on 2025-12-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_income', '0005_add_investment_type_to_funds'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investmentfund',
            unique_together={('user_id', 'fund_name')},
        ),
    ]
