# Generated by Django 5.2.8 on 2025-11-15 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'investment_types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_predefined', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('investment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='configuration.investmenttype')),
            ],
            options={
                'db_table': 'investment_sub_types',
                'ordering': ['investment_type', 'display_order', 'name'],
                'unique_together': {('investment_type', 'code')},
            },
        ),
    ]
