# Generated by Django 5.2.8 on 2025-11-21

from django.db import migrations


def add_bitcoin_subtype_forward(apps, schema_editor):
    """Add Bitcoin as Investment Subtype under Renda Variável em Dólares."""
    InvestmentType = apps.get_model('configuration', 'InvestmentType')
    InvestmentSubType = apps.get_model('configuration', 'InvestmentSubType')
    
    # Get or create Renda Variável em Dólares investment type
    renda_variavel_dolares, _ = InvestmentType.objects.get_or_create(
        code='RENDA_VARIAVEL_DOLARES',
        defaults={
            'name': 'Renda Variável em Dólares',
            'display_order': 20,
            'is_active': True
        }
    )
    
    # Create Bitcoin subtype
    bitcoin_subtype, _ = InvestmentSubType.objects.get_or_create(
        investment_type=renda_variavel_dolares,
        code='BITCOIN',
        defaults={
            'name': 'Bitcoin',
            'display_order': 20,
            'is_predefined': True,
            'is_active': True
        }
    )
    
    print(f"Created Bitcoin subtype under Renda Variável em Dólares")


def add_bitcoin_subtype_reverse(apps, schema_editor):
    """Reverse migration - remove Bitcoin subtype."""
    InvestmentSubType = apps.get_model('configuration', 'InvestmentSubType')
    
    # Delete Bitcoin subtype
    InvestmentSubType.objects.filter(code='BITCOIN').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_bitcoin_subtype_forward, add_bitcoin_subtype_reverse),
    ]
