# Generated by Django 5.2.8 on 2025-11-21

from django.db import migrations


def add_cdb_caixa_subtype_forward(apps, schema_editor):
    """Add CDB CAIXA as Investment Subtype under Renda Fixa."""
    InvestmentType = apps.get_model('configuration', 'InvestmentType')
    InvestmentSubType = apps.get_model('configuration', 'InvestmentSubType')
    
    # Get or create Renda Fixa investment type
    renda_fixa, _ = InvestmentType.objects.get_or_create(
        code='RENDA_FIXA',
        defaults={
            'name': 'Renda Fixa',
            'display_order': 30,
            'is_active': True
        }
    )
    
    # Create CDB CAIXA subtype
    cdb_caixa_subtype, _ = InvestmentSubType.objects.get_or_create(
        investment_type=renda_fixa,
        code='CDB_CAIXA',
        defaults={
            'name': 'CDB CAIXA',
            'display_order': 30,
            'is_predefined': True,
            'is_active': True
        }
    )
    
    print(f"Created CDB CAIXA subtype under Renda Fixa")


def add_cdb_caixa_subtype_reverse(apps, schema_editor):
    """Reverse migration - remove CDB CAIXA subtype."""
    InvestmentSubType = apps.get_model('configuration', 'InvestmentSubType')
    
    # Delete CDB CAIXA subtype
    InvestmentSubType.objects.filter(code='CDB_CAIXA').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_add_bitcoin_subtype'),
    ]

    operations = [
        migrations.RunPython(add_cdb_caixa_subtype_forward, add_cdb_caixa_subtype_reverse),
    ]
