# Generated by Django 5.2.8 on 2025-11-21

from django.db import migrations


def ensure_subtypes_exist_forward(apps, schema_editor):
    """Ensure all required subtypes exist for allocation strategy."""
    InvestmentType = apps.get_model('configuration', 'InvestmentType')
    InvestmentSubType = apps.get_model('configuration', 'InvestmentSubType')
    
    # Get or create Renda Fixa investment type
    renda_fixa, _ = InvestmentType.objects.get_or_create(
        code='RENDA_FIXA',
        defaults={
            'name': 'Renda Fixa',
            'display_order': 30,
            'is_active': True
        }
    )
    
    # Ensure Tesouro Direto subtype exists
    tesouro_subtype, _ = InvestmentSubType.objects.get_or_create(
        investment_type=renda_fixa,
        code='TESOURO_DIRETO',
        defaults={
            'name': 'Tesouro Direto',
            'display_order': 10,
            'is_predefined': True,
            'is_active': True
        }
    )
    
    # Ensure CDB CAIXA subtype exists
    cdb_caixa_subtype, _ = InvestmentSubType.objects.get_or_create(
        investment_type=renda_fixa,
        code='CDB_CAIXA',
        defaults={
            'name': 'CDB CAIXA',
            'display_order': 20,
            'is_predefined': True,
            'is_active': True
        }
    )
    
    # Get or create Renda Variável em Dólares
    renda_variavel_dolares, _ = InvestmentType.objects.get_or_create(
        code='RENDA_VARIAVEL_DOLARES',
        defaults={
            'name': 'Renda Variável em Dólares',
            'display_order': 20,
            'is_active': True
        }
    )
    
    # Ensure BDRs subtype exists
    bdrs_subtype, _ = InvestmentSubType.objects.get_or_create(
        investment_type=renda_variavel_dolares,
        code='BDRS',
        defaults={
            'name': 'BDRs',
            'display_order': 10,
            'is_predefined': True,
            'is_active': True
        }
    )
    
    # Ensure Bitcoin subtype exists (for crypto)
    bitcoin_subtype, _ = InvestmentSubType.objects.get_or_create(
        investment_type=renda_variavel_dolares,
        code='BITCOIN',
        defaults={
            'name': 'Bitcoin',
            'display_order': 20,
            'is_predefined': True,
            'is_active': True
        }
    )
    
    print(f"Ensured all required subtypes exist")


def ensure_subtypes_exist_reverse(apps, schema_editor):
    """Reverse migration - no action needed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_add_cdb_caixa_subtype'),
    ]

    operations = [
        migrations.RunPython(ensure_subtypes_exist_forward, ensure_subtypes_exist_reverse),
    ]
