# Generated by Django 5.2.8 on 2025-11-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('quantidade', models.IntegerField(default=0)),
                ('preco_medio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_total_investido', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('lucro_realizado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'db_table': 'portfolio_positions',
                'ordering': ['ticker'],
                'unique_together': {('user_id', 'ticker')},
            },
        ),
    ]
