# Generated by Django 5.2.8 on 2025-12-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, help_text='Ticker da ação ou FII', max_length=20)),
                ('event_type', models.CharField(choices=[('GROUPING', 'Grupamento (Reverse Split)'), ('SPLIT', 'Desdobramento (Split)'), ('BONUS', 'Bonificação'), ('SUBSCRIPTION', 'Subscrição')], help_text='Tipo de evento corporativo', max_length=20)),
                ('asset_type', models.CharField(choices=[('STOCK', 'Ação'), ('FII', 'Fundo Imobiliário (FII)')], default='STOCK', help_text='Tipo de ativo (Ação ou FII)', max_length=10)),
                ('ex_date', models.DateField(help_text='Data ex-evento (data a partir da qual o evento é efetivo)')),
                ('ratio', models.CharField(help_text="Proporção do evento, ex: '20:1' para grupamento, '1:5' para split", max_length=20)),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada do evento')),
                ('applied', models.BooleanField(default=False, help_text='Indica se o ajuste já foi aplicado ao portfólio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'corporate_events',
                'ordering': ['-ex_date', 'ticker'],
                'indexes': [models.Index(fields=['ticker', 'ex_date'], name='corporate_e_ticker_e4a9e4_idx'), models.Index(fields=['asset_type'], name='corporate_e_asset_t_080bd0_idx')],
            },
        ),
    ]
