# Generated by Django 5.2.8 on 2025-12-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_operations', '0002_corporateevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateevent',
            name='previous_ticker',
            field=models.CharField(blank=True, db_index=True, help_text='Ticker anterior (usado apenas para TICKER_CHANGE)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='corporateevent',
            name='event_type',
            field=models.CharField(choices=[('GROUPING', 'Grupamento (Reverse Split)'), ('SPLIT', 'Desdobramento (Split)'), ('BONUS', 'Bonificação'), ('SUBSCRIPTION', 'Subscrição'), ('TICKER_CHANGE', 'Mudança de Ticker/Nome')], help_text='Tipo de evento corporativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='corporateevent',
            name='ratio',
            field=models.CharField(blank=True, help_text="Proporção do evento, ex: '20:1' para grupamento, '1:5' para split (não usado para TICKER_CHANGE)", max_length=20),
        ),
        migrations.AlterField(
            model_name='corporateevent',
            name='ticker',
            field=models.CharField(db_index=True, help_text='Ticker da ação ou FII (novo ticker para TICKER_CHANGE)', max_length=20),
        ),
    ]
