# Generated by Django 5.2.8 on 2025-12-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_operations', '0003_corporateevent_previous_ticker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateevent',
            name='event_type',
            field=models.CharField(choices=[('GROUPING', 'Grupamento (Reverse Split)'), ('SPLIT', 'Desdobramento (Split)'), ('BONUS', 'Bonificação'), ('SUBSCRIPTION', 'Subscrição'), ('TICKER_CHANGE', 'Mudança de Ticker/Nome'), ('FUND_CONVERSION', 'Extinção/Conversão de Fundo')], help_text='Tipo de evento corporativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='corporateevent',
            name='previous_ticker',
            field=models.CharField(blank=True, db_index=True, help_text='Ticker anterior (usado para TICKER_CHANGE e FUND_CONVERSION - fundo extinto)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='corporateevent',
            name='ratio',
            field=models.CharField(blank=True, help_text="Proporção do evento, ex: '20:1' para grupamento, '1:5' para split, '3:2' para conversão (novas:antigas)", max_length=20),
        ),
        migrations.AlterField(
            model_name='corporateevent',
            name='ticker',
            field=models.CharField(db_index=True, help_text='Ticker da ação ou FII (novo ticker para TICKER_CHANGE/FUND_CONVERSION)', max_length=20),
        ),
    ]
