# Generated by Django 5.2.8 on 2025-11-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TickerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ticker', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ticker_mappings',
                'ordering': ['company_name'],
            },
        ),
    ]
