# Generated by Django 5.2.8 on 2025-11-15 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allocation_strategies', '0001_initial'),
        ('stocks', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RebalancingRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='allocation_strategies.userallocationstrategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebalancing_recommendations', to='users.user')),
            ],
            options={
                'db_table': 'rebalancing_recommendations',
                'ordering': ['-recommendation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RebalancingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('rebalance', 'Rebalance')], max_length=20)),
                ('current_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('target_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('difference', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('quantity_to_buy', models.IntegerField(blank=True, null=True)),
                ('quantity_to_sell', models.IntegerField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rebalancing_actions', to='stocks.stock')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='rebalancing.rebalancingrecommendation')),
            ],
            options={
                'db_table': 'rebalancing_actions',
                'ordering': ['recommendation', 'display_order'],
            },
        ),
    ]
