# Generated by Django 5.2.8 on 2025-11-21 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_ensure_subtypes_exist'),
        ('rebalancing', '0003_add_reason_to_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebalancingaction',
            name='investment_subtype',
            field=models.ForeignKey(blank=True, help_text='Investment subtype for rebalancing actions (e.g., "CDB Pré-fixado", "Tesouro Direto")', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rebalancing_actions', to='configuration.investmentsubtype'),
        ),
        migrations.AddField(
            model_name='rebalancingaction',
            name='subtype_name',
            field=models.CharField(blank=True, help_text='Custom subtype name for actions not linked to a specific subtype', max_length=255, null=True),
        ),
    ]
