# Generated by Django 5.2.8 on 2025-11-13 20:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerageNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=255)),
                ('original_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('note_date', models.CharField(max_length=20)),
                ('note_number', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('operations_count', models.IntegerField(default=0)),
                ('operations', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'brokerage_notes',
                'ordering': ['-note_date', '-note_number'],
                'unique_together': {('user_id', 'note_number', 'note_date')},
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tipo_operacao', models.CharField(max_length=1)),
                ('tipo_mercado', models.CharField(blank=True, max_length=50, null=True)),
                ('ordem', models.IntegerField(default=0)),
                ('titulo', models.CharField(max_length=20)),
                ('qtd_total', models.IntegerField(blank=True, default=0, null=True)),
                ('preco_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantidade', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_operacao', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dc', models.CharField(blank=True, max_length=1, null=True)),
                ('nota_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('corretora', models.CharField(blank=True, max_length=100, null=True)),
                ('nota_number', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.CharField(max_length=20)),
                ('client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_set', to='brokerage_notes.brokeragenote')),
            ],
            options={
                'db_table': 'operations',
                'ordering': ['data', 'ordem'],
            },
        ),
    ]
