# Generated by Django 5.2.8 on 2025-11-26 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0004_alter_stock_investment_type_alter_stock_stock_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIIProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(help_text='e.g., Tijolo:Shoppings', max_length=100)),
                ('target_audience', models.CharField(help_text='e.g., Investidor Qualificado', max_length=100)),
                ('administrator', models.CharField(max_length=255)),
                ('last_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('base_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('average_yield_12m_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rend. Méd. 12m (R$)')),
                ('average_yield_12m_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rend. Méd. 12m (%)')),
                ('equity_per_share', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Patrimônio/Cota')),
                ('price_to_vp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cotação/VP')),
                ('trades_per_month', models.IntegerField(blank=True, null=True, verbose_name='Nº negócios/mês')),
                ('ifix_participation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Partic. IFIX')),
                ('shareholders_count', models.IntegerField(blank=True, null=True, verbose_name='Número Cotistas')),
                ('equity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Patrimônio')),
                ('base_share_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cota base')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fii_profile', to='stocks.stock')),
            ],
            options={
                'verbose_name': 'FII Profile',
                'verbose_name_plural': 'FII Profiles',
                'db_table': 'fii_profiles',
            },
        ),
    ]
