# Generated by Django 5.2.8 on 2025-11-15 18:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        ('stocks', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentTypeAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('display_order', models.IntegerField(default=0)),
                ('investment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='configuration.investmenttype')),
            ],
            options={
                'db_table': 'investment_type_allocations',
                'ordering': ['strategy', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='SubTypeAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, max_length=255, null=True)),
                ('target_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('display_order', models.IntegerField(default=0)),
                ('sub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='configuration.investmentsubtype')),
                ('type_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_type_allocations', to='allocation_strategies.investmenttypeallocation')),
            ],
            options={
                'db_table': 'sub_type_allocations',
                'ordering': ['type_allocation', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='UserAllocationStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_portfolio_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_strategy', to='users.user')),
            ],
            options={
                'db_table': 'user_allocation_strategies',
                'ordering': ['user__name'],
            },
        ),
        migrations.AddField(
            model_name='investmenttypeallocation',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_allocations', to='allocation_strategies.userallocationstrategy'),
        ),
        migrations.CreateModel(
            name='StockAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('display_order', models.IntegerField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='stocks.stock')),
                ('sub_type_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_allocations', to='allocation_strategies.subtypeallocation')),
            ],
            options={
                'db_table': 'stock_allocations',
                'ordering': ['sub_type_allocation', 'display_order'],
                'unique_together': {('sub_type_allocation', 'stock')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='investmenttypeallocation',
            unique_together={('strategy', 'investment_type')},
        ),
    ]
