# Generated by Django 5.2.8 on 2025-12-19 23:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation_strategies', '0001_initial'),
        ('stocks', '0004_alter_stock_investment_type_alter_stock_stock_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIIAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('display_order', models.IntegerField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fii_allocations', to='stocks.stock')),
                ('type_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fii_allocations', to='allocation_strategies.investmenttypeallocation')),
            ],
            options={
                'db_table': 'fii_allocations',
                'ordering': ['type_allocation', 'display_order'],
                'unique_together': {('type_allocation', 'stock')},
            },
        ),
    ]
