# Generated by Django 5.2.8 on 2025-11-13 20:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.CharField(max_length=50)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock_snapshots',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
                ('codigo', models.CharField(db_index=True, max_length=20)),
                ('earning_yield', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nome', models.CharField(max_length=255)),
                ('setor', models.CharField(max_length=255)),
                ('ev', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ebit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('liquidez', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cotacao_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, default='')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='clubedovalor.stocksnapshot')),
            ],
            options={
                'db_table': 'stocks',
                'ordering': ['ranking'],
                'unique_together': {('snapshot', 'codigo')},
            },
        ),
    ]
