# Generated by Django 5.2.8 on 2025-11-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubedovalor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='btm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='cfy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='dividend_yield_36m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='liquidez_media_3m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='mktcap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='value_idx',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stocksnapshot',
            name='strategy_type',
            field=models.CharField(choices=[('AMBB1', 'AMBB 1.0 - Ações mais baratas da bolsa'), ('AMBB2', 'AMBB 2.0 - Ações mais baratas da bolsa'), ('MDIV', 'Máquina de Dividendos'), ('MOM', 'Momentum')], db_index=True, default='AMBB1', max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cotacao_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='earning_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ebit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ev',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='liquidez',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddIndex(
            model_name='stocksnapshot',
            index=models.Index(fields=['strategy_type', 'is_current'], name='stock_snaps_strateg_b5e376_idx'),
        ),
        migrations.AddIndex(
            model_name='stocksnapshot',
            index=models.Index(fields=['strategy_type', '-timestamp'], name='stock_snaps_strateg_d0f2d3_idx'),
        ),
    ]
