# Generated by Django 5.2.8 on 2025-11-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubedovalor', '0002_stock_btm_stock_cfy_stock_dividend_yield_36m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='capitalizacao_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='id_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='momentum_6m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='segmento',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='stock',
            name='subsetor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='stock',
            name='volume_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
