# Generated by Django 5.2.8 on 2025-11-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubedovalor', '0003_stock_capitalizacao_mm_stock_id_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksnapshot',
            name='strategy_type',
            field=models.CharField(choices=[('AMBB1', 'AMBB 1.0 - Ações mais baratas da bolsa'), ('AMBB2', 'AMBB 2.0 - Ações mais baratas da bolsa'), ('MDIV', 'Máquina de Dividendos'), ('MOMM', 'Momentum Melhores'), ('MOMP', 'Momentum Piores')], db_index=True, default='AMBB1', max_length=10),
        ),
    ]
